// See README on how best to update this array
//
//
const protectedArr = [process.env.MYLINKEDIN];
const targetLinks = [
  'https://www.linkedin.com/in/matthew-xing/',
  'https://www.linkedin.com/in/peter-makhnatch/',
  'https://www.linkedin.com/in/jakekazi/',
  'https://www.linkedin.com/in/victorhe33',
  'https://www.linkedin.com/in/tristan-onfroy/',
  'https://www.linkedin.com/in/michaelcolliergrant',
  'https://www.linkedin.com/in/chris-m-kim/',
  'https://www.linkedin.com/in/erika-collins-reynolds',
  'www.linkedin.com/in/holly-nigh',
  'https://www.linkedin.com/in/wvaviator',
  'https://www.linkedin.com/in/elrjolliffe/',
  'https://www.linkedin.com/in/jamesjhuang',
  'https://www.linkedin.com/in/mario-robaina-a8749b229/',
  'https://www.linkedin.com/in/daniel-aurand/',
  'https://www.linkedin.com/in/mariyanovok/',
  'https://www.linkedin.com/in/jason-johnson-2954b1235',
  'https://www.linkedin.com/in/mathew-hultquist/',
  'https://www.linkedin.com/in/jake-ruiz-954535184',
  'https://www.linkedin.com/in/jeffreypettis/',
  'https://www.linkedin.com/in/chentshen',
  'https://www.linkedin.com/in/jessica-davila-5a8380115/',
  'https://www.linkedin.com/in/risaochiai/',
  'www.linkedin.com/in/oliver-zhang-48582121',
  'www.linkedin.com/in/michelle-hindt',
  'https://www.linkedin.com/in/jasonbreen/',
  'https://www.linkedin.com/in/thasanee-puttamadilok-686125243/',
  'https://www.linkedin.com/in/mason-shelton-9ab25521a',
  'https://www.linkedin.com/in/yirou-chen-136881a6/',
  'https://www.linkedin.com/in/chitangchin',
  'https://www.linkedin.com/in/richterlau/',
  'https://www.linkedin.com/in/lewislin9/',
  'https://www.linkedin.com/in/judywuxingyi/',
  'https://www.linkedin.com/in/augustoleal/',
  'https://www.linkedin.com/in/jessica-balding/',
  'https://www.linkedin.com/in/michelle-lee-7b484b53/',
  'https://www.linkedin.com/in/jasonbr/',
  'https://www.linkedin.com/in/laurencediarra/',
  'https://www.linkedin.com/in/ethanmcrae/',
  'https://www.linkedin.com/in/saifbeiruty/',
  'https://www.linkedin.com/in/imma-duverger-112450167/',
  'https://www.linkedin.com/in/roger-wan-9870b6120/',
  'www.linkedin.com/in/jasminezalez',
  'https://www.linkedin.com/in/tim-chang-8600ab1b/',
  'https://www.linkedin.com/in/wilsontr/',
  'https://www.linkedin.com/in/jerikko-agatep/',
  'https://www.linkedin.com/in/chris-iscoding/',
  'https://www.linkedin.com/in/ryan-gause-b6b08616b',
  'https://www.linkedin.com/in/mikeoakes07/',
  'https://www.linkedin.com/in/egkopin/',
  'https://www.linkedin.com/in/aaron-allen-34b80545/',
  'https://www.linkedin.com/in/dnecklesportfolio/',
  'https://www.linkedin.com/in/christian-springer0/',
  'https://www.linkedin.com/in/michael-a-ruiz/',
  'www.linkedin.com/in/lily-hoong-2666991a6',
];
const linkedinArr = [...protectedArr, ...targetLinks];

module.exports = linkedinArr;
